version: '2'

services:
  reactsample:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reactstrap-docker
    restart: always
    ports:
      - "9003:3000"
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    command:
      sh -c "npm run start"