version: '3.5'

services:
  reactstrap-example:
    build: .
    container_name: reactstrap-docker-example
    working_dir: /usr/src/app
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - "9003:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true